name: cricjust_premium
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+30

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^10.1.0

  # UI & Animation
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  flutter_staggered_animations: ^1.1.1
  flip_card: ^0.7.0
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.1.0

  # Core
  http: ^1.2.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  url_launcher: ^6.1.5
  path_provider: ^2.1.1
  connectivity_plus: ^6.1.5

  # Media & Display
  flutter_html: ^3.0.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.4
  share_plus: ^11.1.0
  fl_chart: ^0.63.0

  image_cropper:
  audioplayers: ^6.5.0
  confetti: ^0.8.0
  crypto: ^3.0.3
  youtube_player_iframe: ^5.2.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1
  material_symbols_icons: ^4.2719.0

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI Feedback
  another_flushbar: ^1.10.29
  permission_handler: ^12.0.1
  wakelock_plus: ^1.3.2
  fluttertoast: ^8.2.6

  # Live Streaming Dependencies
  camera: ^0.11.0+2
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - lib/asset/images/app_icon.png
    - lib/asset/images/light_theme.png
    - lib/asset/images/dark_theme.png
    - lib/asset/images/cricjust_logo.png
    - lib/asset/images/Random_Image.png
    - lib/asset/images/Theme1.png
    - lib/asset/images/tv_bg.png
    - lib/asset/images/stadium_header.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/asset/images/app_icon.png"
  adaptive_icon_background: "#0288D1"
  adaptive_icon_foreground: "lib/asset/images/app_icon.png"

flutter_native_splash:
  color: "#0288D1"
  image: "lib/asset/images/light_theme.png"
  android: true
  ios: true
  fullscreen: true
